version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "no" # Disable anonymous access for Zookeeper
      ZOO_ENABLE_AUTH: "yes"
      ZOO_SERVER_USERS: "admin"
      ZOO_SERVER_PASSWORDS: "123"
    ports:
      - "2181:2181"

  kafka1:
    image: bitnami/kafka:latest
    container_name: kafka1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT"
      KAFKA_CFG_ADVERTISED_LISTENERS: "SASL_PLAINTEXT://localhost:9092"
      KAFKA_CFG_LISTENERS: "SASL_PLAINTEXT://0.0.0.0:9092"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "SASL_PLAINTEXT"
      KAFKA_CFG_SASL_ENABLED_MECHANISMS: "PLAIN"
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"
      KAFKA_CLIENT_USERS: "admin"
      KAFKA_CLIENT_PASSWORDS: "123"
    ports:
      - "9092:9092"
 
  kafka2:
    image: bitnami/kafka:latest
    container_name: kafka2
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT"
      KAFKA_CFG_ADVERTISED_LISTENERS: "SASL_PLAINTEXT://localhost:9093"
      KAFKA_CFG_LISTENERS: "SASL_PLAINTEXT://0.0.0.0:9093"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "SASL_PLAINTEXT"
      KAFKA_CFG_SASL_ENABLED_MECHANISMS: "PLAIN"
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"
      KAFKA_CLIENT_USERS: "admin"
      KAFKA_CLIENT_PASSWORDS: "123"
    ports:
      - "9093:9093"
 
  kafka3:
    image: bitnami/kafka:latest
    container_name: kafka3
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT"
      KAFKA_CFG_ADVERTISED_LISTENERS: "SASL_PLAINTEXT://localhost:9094"
      KAFKA_CFG_LISTENERS: "SASL_PLAINTEXT://0.0.0.0:9094"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "SASL_PLAINTEXT"
      KAFKA_CFG_SASL_ENABLED_MECHANISMS: "PLAIN"
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"
      KAFKA_CLIENT_USERS: "admin"
      KAFKA_CLIENT_PASSWORDS: "123"
    ports:
      - "9094:9094"
   
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on: 
      - kafka1
      - kafka2
      - kafka3 
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: broker
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092,kafka2:9093,kafka3:9094
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    restart: always